### PR TITLE
First PS3 Submission

### PR DESCRIPTION
**Pull request by kiekhaec**

### CODE REVIEW

**Comment by kriemo** [comment]
Can you run `knit` on your Rmarkdown and commit/push the generated `.html` file also? Thanks

**Comment by kiekhaec** [comment]
I did as requested and would like to know if it transferred.


Attached is what is see on my screen.


Thanks VERY much for your tutoring on Friday!  The discussion was a great benefit for me in understanding how to use R.


Carol
Carol Kiekhaefer, MD, PhD
University of Colorado
Anschutz Medical Campus
Aurora, CO 80045
Phone: 608-235-3302



________________________________

**Comment by kriemo** [comment]
The .html did not get transferred. Make sure to select the box next to the .html file in your git tab, then commit.

**Comment by kiekhaec** [comment]
The git tab has nothing to select.  I closed R, reopened the project, reknitted the file and it still has no entries in the git tab.


Please advise and I will do accordingly.[😊]

Carol
Carol Kiekhaefer, MD, PhD
Laboratory of Dr. Sarah Faubel
University of Colorado
Anschutz Medical Campus
RC-2, 7th Floor
Room 7410D
12700 East 19th Ave
Aurora, CO 80045
Phone: 608-235-3302



________________________________

**Comment by kriemo** [comment]
OK. I'll take a look at this issue tomorrow at class. Thanks.

**Comment by kiekhaec** [comment]
Thanks,


See you tomorrow.

Carol
Carol Kiekhaefer, MD, PhD
University of Colorado
Anschutz Medical Campus
Aurora, CO 80045
Phone: 608-235-3302



________________________________

**Comment by kiekhaec** [comment]
Here is my rpubs link: http://rpubs.com/cmkiekha/256701

**Comment by kriemo** [comment]
Strong work 👍

**Pull request closed without merging**
