### PR TITLE
Problem set 3

### PR DESCRIPTION
**Pull request by chrismit258**

### CODE REVIEW

**Comment by kriemo** [comment]
Can you knit your RMarkdown to html and submit the knit'ed html file also? Thanks!

**Comment by chrismit258** [comment]
I had already knitted it to html before I submitted. I'm not sure why the html file didn't go through? I am using git separately from R because I'm on a PC so the submission process is not so straightforward. Please let me know if you have any tips to make sure the html file goes through.

**Comment by lkwhite** [comment]
Yeah, there's something weird going on with the latest PC version of Rstudio, Git, and committing knitted .html files. One alternative that we used last year was to have students upload their knitted final problem set to [Rpubs](https://rpubs.com/).

**Comment by kriemo** [comment]
Thanks @lkwhite. Christy because of this issue you do need need to submit the .html.

**Comment by chrismit258** [comment]
I just published it to Rpubs under the username chrismit258, in case that's helpful.

**Comment by kriemo** [comment]
great. Thanks!

**Comment by kriemo** [comment]
Strong work 👍

**Pull request closed without merging**
